# <font color='brown'>100 NumPy Exercises</font>

## Introduction

![numpylogo.png](attachment:numpylogo.png)

**NumPy** is an extension library for Python language, supporting operations of a large number of high-dimensional arrays and matrices. In addition, it also provides a large number of mathematical function libraries for array operations. Machine learning involves a lot of transformations and operations on arrays, which makes NumPy one of the essential tools.

**100 NumPy Exercises** is divided into _basic part_ and _advanced part_, each with 50 exercises. The basic part of the exercise helps you familiarize yourself with the use of NumPy's common methods and the advanced part focuses on the combined application of the NumPy methods.

If you already have a foundation for NumPy before you take the course, you can review it in the following cells. If you are unfamiliar with NumPy, make sure you **manually** practice in the blank cells below each example cell.

### Knowledge Points

The main points covered in this experiment are:
- Creating an array
- Array operation
- Mathematical functions
- Array slices and indexes
- Array shape operations
- Array sorting
- Array statistics

### Environment

- Python 3.6
- NumPy 1.14.2

### Catalog Index

- <a href="#1">1. Basic Part</a>
- <a href="#2">2. Advanced Part</a>
- <a href="#3">3. Summary</a>

---

## <a id = "1">1. Basic Part</a>

### Import NumPy

#### 1. Import NumPy
Before practicing **NumPy**, first you need to import the `numpy` module, and the convention is abbreviated as `np`:

In [ ]:
import numpy as np

In [1]:

import numpy as np

#### 2. View NumPy version  

In [ ]:
print(np.__version__)

In [2]:
print(np.__version__)

1.22.4


### Create an Array

The main object of **NumPy** is the multidimensional array `ndarray`. In NumPy, `dimensions` are called `axes`, and the number of axes is called `rank`.

For example, the array below is an array of rank 1, because it has only one axis and the length of the axis is 3:
```
[1, 2, 3]
```

For another example, the rank of this array is 2. The first dimension length is 2 and the second dimension length is 3:

```
[[1., 2., 3.],
 [4., 5., 6.]]
```

#### 3. Create a one-dimensional array from a list

**Note:** `numpy.array` is not the same as the Python standard library `array.array`. The former is more powerful, which is one of the important reasons why we learn `Numpy`:

In [ ]:
np.array([1,2,3])

In [3]:
np.array([1,2,3])

array([1, 2, 3])

#### 4. Create a two-dimensional array from a list

In [ ]:
np.array([(1,2,3),(4,5,6)])

In [4]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

#### 5. Create a two-dimensional array full of `0`

In [ ]:
np.zeros((3,3))

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 6. Create a three-dimensional array full of `1`

In [ ]:
np.ones((2,3,4))

In [6]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Note: Please think about the dimensional relationships of the above 4 arrays.

#### 7. Create a one-dimensional arithmetic progression array

In [ ]:
np.arange(5)

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

#### 8. Create a two-Dimensional arithmetic progression array

In [ ]:
np.arange(6).reshape(2,3)

In [8]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

#### 9. Create a unit matrix (two-dimensional array)

In [ ]:
np.eye(3)

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 10. Create equally spaced one-dimensional array

In [ ]:
np.linspace(1, 10, num=6)

In [10]:
np.linspace(1, 10, num=6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

#### 11. Create two-dimensional random array 

In [ ]:
np.random.rand(2,3)

In [11]:
np.random.rand(2,3)

array([[0.29994737, 0.05586861, 0.00665447],
       [0.91388502, 0.72045488, 0.95604927]])

#### 12. Create two-dimensional random integer array (value < 5)

In [ ]:
np.random.randint(5, size=(2,3))

In [12]:
np.random.randint(5, size=(2,3))

array([[4, 0, 2],
       [3, 3, 2]])

#### 13. Create an array based on a custom function

In [ ]:
np.fromfunction(lambda i, j: i + j, (3, 3))

In [13]:
np.fromfunction(lambda i, j: i + j, (3, 3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

### Array Operations

#### Generate a one-dimensional example array

In [ ]:
a = np.array([10,20,30,40,50])
b = np.arange(1,6)
a,b

In [14]:
a = np.array([10,20,30,40,50])
b = np.arange(1,6)
a,b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

#### 14. One-dimensional array addition


In [ ]:
a + b

In [15]:
a + b

array([11, 22, 33, 44, 55])

#### 15. One-dimensional array subtraction

In [ ]:
a - b

In [16]:
a - b

array([ 9, 18, 27, 36, 45])

#### 16. One-dimensional array multiplication

In [ ]:
a * b

In [17]:
a * b

array([ 10,  40,  90, 160, 250])

#### 17. One-dimensional array division

In [ ]:
a / b

In [18]:
a / b

array([10., 10., 10., 10., 10.])

#### Generate a two-dimensional example array (can be seen as a matrix)

In [ ]:
A = np.array([[1,2],
           [3,4]])
B = np.array([[5,6],
           [7,8]])
A, B

In [19]:
A = np.array([[1,2],
           [3,4]])
B = np.array([[5,6],
           [7,8]])
A, B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

#### 18. Matrix addition

In [ ]:
A + B

In [20]:
A + B

array([[ 6,  8],
       [10, 12]])

#### 19. Matrix subtraction

In [ ]:
A - B

In [21]:
A - B

array([[-4, -4],
       [-4, -4]])

#### 20. Multiplication between matrix elements

In [ ]:
A * B

In [22]:
A * B

array([[ 5, 12],
       [21, 32]])

#### 21. Matrix multiplication (Note the difference between 21 and 20)

In [ ]:
np.dot(A, B)

In [23]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [ ]:
# If you use np.mat to accurately define a two-dimensional array as a matrix, you can use * to complete the matrix multiplication.
np.mat(A) * np.mat(B)

In [24]:
np.mat(A) * np.mat(B)

matrix([[19, 22],
        [43, 50]])

#### 22. Multiplication between matrix and number

In [ ]:
2 * A

In [25]:
2*A

array([[2, 4],
       [6, 8]])

#### 23. Transpose of matrix

In [ ]:
A.T

In [26]:
A.T

array([[1, 3],
       [2, 4]])

#### 24. Matrix inversion

In [ ]:
np.linalg.inv(A)

In [27]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Mathematical Functions

#### 25. Trigonometric functions

In [ ]:
print(a)

np.sin(a)

In [28]:
print(a)

np.sin(a)

[10 20 30 40 50]


array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

#### 26. Exponential function based on natural logarithm function

In [ ]:
np.exp(a)

In [29]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

#### 27. Square root of the array (extraction of square root)

In [ ]:
np.sqrt(a)

In [30]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

#### 28. Square root of the array（cube）

In [ ]:
np.power(a, 3)

In [31]:
np.power(a, 3)

array([  1000,   8000,  27000,  64000, 125000])

### Array Slices and Indexes

#### 29. One-dimensional array index

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a[0], a[-1]

In [32]:
a = np.array([1, 2, 3, 4, 5])
a[0], a[-1]

(1, 5)

#### 30. One-dimensional array slice

In [ ]:
a[0:2], a[:-1]

In [33]:
a[0:2], a[:-1]

(array([1, 2]), array([1, 2, 3, 4]))

#### 31. Two-dimensional array index

In [ ]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a[0], a[-1]

In [34]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a[0], a[-1]

(array([1, 2, 3]), array([7, 8, 9]))

#### 32. Two-dimensional array slice (use the second column)

In [ ]:
print(a)

a[:, 1]

In [35]:
print(a)

a[:, 1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 5, 8])

#### 33. Two-dimensional array slice (use the second, third columns)

In [ ]:
a[1:3, :]

### Array Shape Operations

#### Generate a two-dimensional example array

In [ ]:
a = np.random.random((3, 2))
a

#### 34. Check out array shape

In [ ]:
a.shape

#### 35. Change array shape (without changing the origin array)

In [ ]:
# reshape doesn't change the original array
a.reshape(2, 3)

In [ ]:
a

#### 36. Change array shape（change the origin array）

In [ ]:
# resize changes the original array
a.resize(2, 3) 

In [ ]:
a

#### 37. Ravel array

In [ ]:
a.ravel()

#### 38. Vertically splice arrays

In [ ]:
# Generate the example arrays
a = np.random.randint(10, size=(3, 3))
b = np.random.randint(10, size=(3, 3))

a, b

In [ ]:
np.vstack((a, b))

#### 39. Horizontally splice arrays

In [ ]:
np.hstack((a, b))

#### 40. Split array along the horizontal axis

In [ ]:
np.hsplit(a, 3)

#### 41. Split array along the vertical axis

In [ ]:
np.vsplit(a, 3)

### Array Sorting

In [ ]:
# Generate example array
a = np.array(([1,4,3],[6,2,9],[4,7,2]))
a

#### 42. Return the maximum value of each column 

In [ ]:
np.max(a, axis=0)

#### 43. Return the minimum value of each column 

In [ ]:
np.min(a, axis=1)

#### 44. Return the index of the max value of each column

In [ ]:
np.argmax(a, axis=0)

#### 45. Return the index of the min value of each column

In [ ]:
np.argmin(a, axis=1)

### Array Statistics

#### 46. Statistics of the median of each column of the array

In [ ]:
# Keep using array a
np.median(a, axis=0)

#### 47. Statistics of the arithmetic mean value of each row of the array

In [ ]:
np.mean(a, axis=1)

#### 48. Statistics of the weighted average of each column of the array


In [ ]:
np.average(a, axis=0)

#### 49. Statistics of the variance of each row of the array

In [ ]:
np.var(a, axis=1)

#### 50. Statistics of the standard deviation of each column of the array 

In [ ]:
np.std(a, axis=0)

---
##  <a id = "2">2. Advanced Part [Optional]</a>

#### 51. Create a 5x5 two-dimensional array, the boundary value is 0, and the rest is 0

In [ ]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
Z

#### 52. Use number `0` to surround a 5x5 two-dimensional array full of `1`

In [ ]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

#### 53. Create a 5x5 two-dimensional array, and set the values `1, 2, 3, 4` to fall below its diagonal line

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
Z

#### 54. Create a 10x10 two-dimensional array, and let `1` and `0` be placed diagonally 

In [ ]:
Z = np.zeros((10,10),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

#### 55. Create a `0`-`10` one-dimensional array and make the numbers between (`1`, `9`] all inverted to negative numbers

In [ ]:
Z = np.arange(11)
Z[(1 < Z) & (Z <= 9)] *= -1
Z

#### 56. Find the same elements in two one-dimensional arrays

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print("Z1: ", Z1)
print("Z2: ", Z2)
np.intersect1d(Z1,Z2)

#### 57. Use NumPy to print the datesof yesterday, today nd tomorrow

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("yesterday: ", yesterday)
print("today: ", today)
print("tomorrow: ", tomorrow)

#### 58. Use five different methods to extract the integer part of a random array

In [ ]:
Z = np.random.uniform(0,10,10)
print("Original value: ", Z)

print ("method 1: ", Z - Z%1)
print ("method 2: ", np.floor(Z))
print ("method 3: ", np.ceil(Z)-1)
print ("method 4: ", Z.astype(int))
print ("method 5: ", np.trunc(Z))

#### 59. Create a 5x5 matrix, the values in each row range from `1` to `5`

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(1,6)

Z

#### 60. Create an equally spaced one-dimensional array of length `5` with values ranging from `0` to `1`, but not including `0` and `1`

In [ ]:
Z = np.linspace(0,1,6,endpoint=False)[1:]

Z

#### 61. Create a random one-dimensional array of length 10 and sort it in ascending order 

In [ ]:
Z = np.random.random(10)
Z.sort()
Z

#### 62. Create a 3x3 2D array and sort the columns in ascending order

In [ ]:
Z = np.array([[7,4,3],[3,1,2],[4,2,6]])
print("Original array: \n", Z)

Z.sort(axis=0)
Z

#### 63. Create a one-dimensional array of length 5 and replace the maximum value with `0`

In [ ]:
Z = np.random.random(5)
print("Original array: ",Z)
Z[Z.argmax()] = 0
Z

#### 64. Print the minimum value and the maximum value for each NumPy scalar type

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print("The minimum value of {}: ".format(dtype), np.iinfo(dtype).min)
   print("The maximum value of {}: ".format(dtype),np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print("The minimum value of {}: ".format(dtype),np.finfo(dtype).min)
   print("The maximum value of {}: ".format(dtype),np.finfo(dtype).max)

#### 65. Convert `float32` to integer

In [ ]:
Z = np.arange(10, dtype=np.float32)
print(Z)

Z = Z.astype(np.int32, copy=False)
Z

#### 66. Arrange random two-dimensional array in ascending order top to bottom in column 3

In [ ]:
Z = np.random.randint(0,10,(5,5))
print("Before：\n",Z)

Z[Z[:,2].argsort()]

#### 67. From a random one-dimensional array, find the number nearest to the given value (`0.5`)

In [ ]:
Z = np.random.uniform(0,1,20)
print("Random array: \n", Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]

m

#### 68. Swap the first two lines of a two-dimensional array sequentially 

In [ ]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

#### 69. Find the most frequent values in a random one-dimensional array

In [ ]:
Z = np.random.randint(0,10,50)
print("Random one-dimensional array: ", Z)
np.bincount(Z).argmax()

#### 70. Find the position index of non-zero elements in a given one-dimensional array

In [ ]:
Z = np.nonzero([1,0,2,0,1,0,4,0])
Z

#### 71. Randomly place _p_ numbers with the value `1` into a given 5x5 two-dimensional array

In [ ]:
p = 3

Z = np.zeros((5,5))
np.put(Z, np.random.choice(range(5*5), p, replace=False),1)

Z

#### 72. For a random 3x3 two-dimensional array, subtract the average of each row in the array

In [ ]:
X = np.random.rand(3, 3)
print(X)

Y = X - X.mean(axis=1, keepdims=True)
Y

#### 73. Get a diagonal array of two-dimensional array dot product results

In [ ]:
A = np.random.uniform(0,1,(3,3))
B = np.random.uniform(0,1,(3,3))

print(np.dot(A, B))

# A slower method 
np.diag(np.dot(A, B))

In [ ]:
# A fast method 
np.sum(A * B.T, axis=1)

In [ ]:
# A faster method 
np.einsum("ij, ji->i", A, B)

#### 74. In a one-dimensional array, find the top _p_ maxima

In [ ]:
Z = np.random.randint(1,100,100)
print(Z)

p = 5

Z[np.argsort(Z)[-p:]]

#### 75. Compute the fourth power of each element in a random one-dimensional array

In [ ]:
x = np.random.randint(2,5,5)
print(x)

np.power(x,4)

#### 76. For each element in a two-dimensional random array, retain its 2 decimal places

In [ ]:
Z = np.random.random((5,5))
print(Z)

np.set_printoptions(precision=2)
Z

#### 77. Output NumPy array using scientific notation

In [ ]:
Z = np.random.random([5,5])
print(Z)

Z/1e3

#### 78. Use NumPy to find percentiles(25%，50%，75%)

In [ ]:
a = np.arange(15)
print(a)

np.percentile(a, q=[25, 50, 75])

#### 79. Find the total number and locations of missing values in the array

In [ ]:
# Generate a two-dimensional array with missing values
Z = np.random.rand(10,10)
Z[np.random.randint(10, size=5), np.random.randint(10, size=5)] = np.nan
Z

In [ ]:
print("Total number of missing values: \n", np.isnan(Z).sum())
print("Indexes of missing values: \n", np.where(np.isnan(Z)))

#### 80.  Remove rows that contain missing values from a random array

In [ ]:
# Use the array in practice 79

Z[np.sum(np.isnan(Z), axis=1) == 0]

#### 81. Count the number of elements in the random number group

In [ ]:
Z = np.random.randint(0,100,25).reshape(5,5)
print(Z)

np.unique(Z, return_counts=True) # # In the output, the elements in the second array are corresponding numbers of the elements in the first array  

#### 82.  Convert each element in the array to a text value by the specified classification

In [ ]:
# classification:
# 1 → car
# 2 → bus
# 3 → train


Z = np.random.randint(1,4,10)
print(Z)

label_map = {1: "car", 2: "bus", 3: "train"}

[label_map[x] for x in Z]

#### 83.  Combine multiple one-dimensional arrays into a single Ndarray

In [ ]:
Z1 = np.arange(3)
Z2 = np.arange(3,7)
Z3 = np.arange(7,10)

Z = np.array([Z1, Z2, Z3])
print(Z)

np.concatenate(Z)

#### 84. Print the indexes of the elements in the array in ascending order

In [ ]:
a = np.random.randint(100, size=10)
print('Array: ', a)

a.argsort()

#### 85. Get the maximum value of each row of a two-dimensional random array

In [ ]:
Z = np.random.randint(1,100, [5,5])
print(Z)

np.amax(Z, axis=1)

#### 86. Get the minimum value of each row of a two-dimensional random array (Note the difference)

In [ ]:
Z = np.random.randint(1,100, [5,5])
print(Z)

np.apply_along_axis(np.min, arr=Z, axis=1)

#### 87. Calculate the Euclidean distance between two arrays

In [ ]:
a = np.array([1, 2])
b = np.array([7, 8])

# Compute by math
print(np.sqrt(np.power((8-2), 2) + np.power((7-1), 2)))

# Compute by NumPy 
np.linalg.norm(b-a)

#### 88. Print the real and imaginary parts of the complex numbers

In [ ]:
a = np.array([1 + 2j, 3 + 4j, 5 + 6j])

print("real：", a.real)
print("imaginary：", a.imag)

#### 89. Solve the inverse matrix of the given matrix and verify it

In [ ]:
matrix = np.array([[1., 2.], [3., 4.]])

inverse_matrix = np.linalg.inv(matrix)

# Verify whether the dot product of the original matrix and the inverse matrix is an identity matrix
assert np.allclose(np.dot(matrix, inverse_matrix), np.eye(2))
assert np.allclose(np.dot(matrix, inverse_matrix), np.eye(2))

inverse_matrix

#### 90. Standardize data using Z-Score normalization algorithms

Z-Score formula：
$$Z = \frac{X-\mathrm{mean}(X)}{\mathrm{sd}(X)}$$

In [ ]:
# Define the function by formula
def zscore(x, axis = None):
    xmean = x.mean(axis=axis, keepdims=True)
    xstd  = np.std(x, axis=axis, keepdims=True)
    zscore = (x-xmean)/xstd
    return zscore

# Generate random data  
Z = np.random.randint(10, size=(5,5))
print(Z)

zscore(Z)

#### 91. Standardize data using Min-Max standardized algorithms

Min-Max formula：
$$Y = \frac{Z-\min(Z)}{\max(Z)-\min(Z)}$$

In [ ]:
# Define the function by formula
def min_max(x, axis=None):
    min = x.min(axis=axis, keepdims=True)
    max = x.max(axis=axis, keepdims=True)
    result = (x-min)/(max-min)
    return result

# Generate random data
Z = np.random.randint(10, size=(5,5))
print(Z)

min_max(Z)

#### 92. Standardize data using the L2 norm

Formula to get L2 norm:
$$L_2 = \sqrt{x_1^2 + x_2^2 + \ldots + x_i^2}$$

In [ ]:
# Define the function by formula
def l2_normalize(v, axis=-1, order=2):
    l2 = np.linalg.norm(v, ord = order, axis=axis, keepdims=True)
    l2[l2==0] = 1
    return v/l2

# Generate random data
Z = np.random.randint(10, size=(5,5))
print(Z)

l2_normalize(Z)

#### 93. Calculate the direct correlation coefficient of variables by NumPy

In [ ]:
Z = np.array([
    [1, 2, 1, 9, 10, 3, 2, 6, 7], # Feature A
    [2, 1, 8, 3, 7, 5, 10, 7, 2], # Feature B
    [2, 1, 1, 8, 9, 4, 3, 5, 7]]) # Feature C

np.corrcoef(Z)

The correlation coefficient takes a value from `0`-`1`; and a value close to `1` means that the correlation is strong. The results are as follows: The direct correlation coefficient between variable `A` and variable `A` is `1` because it is the same variable; the correlation coefficient between variable `A` and variable `B` is `-0.06`, indicating that they are almost unrelated. The correlation coefficient between variable `A` and variable `C` is `0.97`, indicating a strong correlation:
```
         [A]     [B]     [C]
array([[ 1.  , -0.06,  0.97]   [A]
       [-0.06,  1.  , -0.01],  [B]
       [ 0.97, -0.01,  1.  ]]) [C]
```

#### 94. Calculate the eigenvalues and the eigenvectors of a matrix by using NumPy

In [ ]:
M = np.matrix([[1,2,3], [4,5,6], [7,8,9]])

w, v = np.linalg.eig(M)

# w for eigenvalues，v for eigenvectors
w, v

We can use the `P'AP=M` formula to calculate whether we can get the original matrix:

In [ ]:
v * np.diag(w) * np.linalg.inv(v)

#### 95. Calculate the difference between two adjacent elements of Ndarray by using NumPy

In [ ]:
Z = np.random.randint(1,10,10)
print(Z)

# Calculate the difference between two adjacent elements of Z
print(np.diff(Z, n=1))

# Repeat calculation 2 times
print(np.diff(Z, n=2))

# Repeat calculation 3 times
print(np.diff(Z, n=3))

#### 96. Use NumPy to add the adjacent elements of Ndarray in order 


In [ ]:
Z = np.random.randint(1,10,10)
print(Z)

"""
[First element, first element + second element, first element + second element + third element, ...]
"""
np.cumsum(Z)

#### 97. Use NumPy to connect two arrays by column

In [ ]:
M1 = np.array([1, 2, 3])
M2 = np.array([4, 5, 6])

np.c_[M1, M2]

#### 98. Use NumPy to connect two arrays by row

In [ ]:
M1 = np.array([1, 2, 3])
M2 = np.array([4, 5, 6])

np.r_[M1, M2]

#### 99. Print the 9x9 multiplication table using `NumPy`

In [ ]:
np.fromfunction(lambda i, j: (i + 1) * (j + 1), (9, 9))

#### 100. Convert the LabEx LOGO to an Ndarray using Numpy

In [ ]:
from io import BytesIO
from PIL import Image
import PIL, requests

# Download the image by the URL
URL = 'https://static.shiyanlou.com/img/logo-black.png'
response = requests.get(URL)

# Read the content as image
I = Image.open(BytesIO(response.content))

# Convert the image into Ndarray
labex = np.asarray(I)
labex

In [ ]:
# Redraw the converted Ndarray into an image
from matplotlib import pyplot as plt
%matplotlib inline

plt.imshow(shiyanlou)
plt.show()

## <a id = "3">3. Summary</a>

If you have done the above 100 exercises by yourself, I believe that you have improved your proficiency in the `Numpy` module. We recommend that you review these topics regularly, and you will be more familiar with it. The main points involved in this experiment are:

- Creating an array
- Array operations
- Mathematical functions
- Array slices and indexes
- Array shape operations
- Array sorting
- Array statistics

---

<div style="color: #999;font-size: 12px;font-style: italic;">*本课程内容，由作者授权实验楼发布，未经允许，禁止转载、下载及非法传播。实验中少量题目编译自：[100 numpy exercises](https://github.com/rougier/numpy-100) 。</div>